export const mods = [
    { name: 'FLIB', author: 'Lothrazar', url: 'https://www.curseforge.com/minecraft/mc-mods/flib' },
    { name: 'Jumpy Boats', author: 'LobsterJonn', url: 'https://www.curseforge.com/minecraft/mc-mods/jumpy-boats' },
    { name: 'Eidolon:Repraised', author: 'Alexth99', url: 'https://www.curseforge.com/minecraft/mc-mods/eidolon-repraised'},
    { name: 'Gateways to Eternity', author: 'Shadows_of_Fire', url: 'https://www.curseforge.com/minecraft/mc-mods/gateways-to-eternity'},
    { name: 'MmmMmmMmmMmm (Target Dummy)', author: 'MehVahdJukaar', url: 'https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm'},
    { name: 'Macaw\'s Fences - Biomes O\' Plenty', author: 'Samlegamer_', url: 'https://www.curseforge.com/minecraft/mc-mods/macaws-fences-biomes-o-plenty'},
    { name: 'SmartBrainLib (Forge/Fabric/Quilt)', author: 'Scimiguy', url: 'https://www.curseforge.com/minecraft/mc-mods/smartbrainlib'},
    { name: 'Ars Creo', author: 'baileyholl2', url: 'https://www.curseforge.com/minecraft/mc-mods/ars-creo'},
    { name: 'MrCrayfish\'s Furniture Mod', author: 'MrCrayfish', url: 'https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod'},
    { name: 'Super Factory Manager ( SFM )', author: 'TeamDman', url: 'https://www.curseforge.com/minecraft/mc-mods/super-factory-manager'},
    { name: 'Applied Energistics 2', author: 'thetechnici4n', url: 'https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2'},
    { name: 'Hyperbox', author: 'Commoble', url: 'https://www.curseforge.com/minecraft/mc-mods/hyperbox'},
    { name: 'DefaultSettings', author: 'PT400C', url: 'https://www.curseforge.com/minecraft/mc-mods/defaultsettings'},
    { name: 'YUNG\'s Better Desert Temples (Forge)', author: 'YUNGNICKYOUNG', url: 'https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples'},
    { name: 'FTB Ultimine (Forge)', author: 'FTB', url: 'https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine-forge'},
    { name: 'Almost Unified', author: 'AlmostReliable', url: 'https://www.curseforge.com/minecraft/mc-mods/almost-unified'},
    { name: 'Better Advancements', author: 'way2muchnoise', url: 'https://www.curseforge.com/minecraft/mc-mods/better-advancements'},
    { name: 'FTB Library (Forge)', author: 'FTB', url: 'https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge'},
    { name: 'McJtyLib', author: 'McJty', url: 'https://www.curseforge.com/minecraft/mc-mods/mcjtylib'},
    { name: 'AE2 Insert Export Card', author: 'Ultramegaaa', url: 'https://www.curseforge.com/minecraft/mc-mods/ae2-insert-export-card'},
    { name: 'Gravitational Modulating Additional Unit', author: 'gisellevonbingen', url: 'https://www.curseforge.com/minecraft/mc-mods/gravitational-modulating-additional-unit'},
    { name: 'Macaw\'s Doors', author: 'sketch_macaw', url: 'https://www.curseforge.com/minecraft/mc-mods/macaws-doors'},
    { name: 'Twilight\'s Flavors & Delight', author: 'lcy0x1', url: 'https://www.curseforge.com/minecraft/mc-mods/twilights-flavors-delight'},
    { name: 'YUNG\'s Better Nether Fortresses (Forge)', author: 'YUNGNICKYOUNG', url: 'https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses'},
    { name: 'YUNG\'s Extras (Forge)', author: 'YUNGNICKYOUNG', url: 'https://www.curseforge.com/minecraft/mc-mods/yungs-extras'},
    { name: 'RFTools Utility', author: 'McJty', url: 'https://www.curseforge.com/minecraft/mc-mods/rftools-utility'},
    { name: 'Rhino', author: 'LatvianModder', url: 'https://www.curseforge.com/minecraft/mc-mods/rhino'},
    { name: 'AttributeFix', author: 'DarkhaxDev', url: 'https://www.curseforge.com/minecraft/mc-mods/attributefix'},
    { name: 'Yeetus Experimentus', author: 'Sunekaer', url: 'https://www.curseforge.com/minecraft/mc-mods/yeetusexperimentus'},
    { name: 'Mekanism Generators', author: 'bradyaidanc', url: 'https://www.curseforge.com/minecraft/mc-mods/mekanism-generators'},
    { name: 'libIPN', author: 'mirinimi', url: 'https://www.curseforge.com/minecraft/mc-mods/libipn'},
    { name: 'ChemLib', author: 'Dark_Arcana', url: 'https://www.curseforge.com/minecraft/mc-mods/chemlib'},
    { name: 'Mahou Tsukai', author: 'stepcros', url: 'https://www.curseforge.com/minecraft/mc-mods/mahou-tsukai'},
    { name: 'Epic Samurai\'s - Forge', author: 'VeroxUniverse', url: 'https://www.curseforge.com/minecraft/mc-mods/epic-samurais'},
    { name: 'Village Artifacts', author: 'Lothrazar', url: 'https://www.curseforge.com/minecraft/mc-mods/villager-tools'},
    { name: 'Baubley Heart Canisters', author: 'traverse_joe', url: 'https://www.curseforge.com/minecraft/mc-mods/baubley-heart-canisters'},
    { name: 'Create Confectionery', author: 'Furti_Two', url: 'https://www.curseforge.com/minecraft/mc-mods/create-confectionery'},
    { name: 'FTB Chunks (Forge)', author: 'FTB', url: 'https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge'},
    { name: 'Thermal Extra', author: 'Mrthomas20121', url: 'https://www.curseforge.com/minecraft/mc-mods/thermal_extra'},
    { name: 'YUNG\'s Better Ocean Monuments (Forge)', author: 'YUNGNICKYOUNG', url: 'https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments'},
    { name: 'ExtendedAE', author: 'GlodBlock', url: 'https://www.curseforge.com/minecraft/mc-mods/ex-pattern-provider'},
    { name: 'playerAnimator', author: 'KosmX', url: 'https://www.curseforge.com/minecraft/mc-mods/playeranimator'},
    { name: 'Harvest with ease', author: 'CrystalSpider', url: 'https://www.curseforge.com/minecraft/mc-mods/harvest-with-ease'},
    { name: 'Just Enough Professions (JEP)', author: 'Mrbysco', url: 'https://www.curseforge.com/minecraft/mc-mods/just-enough-professions-jep'},
    { name: 'L_Ender \'s Cataclysm', author: 'mcl_ender', url: 'https://www.curseforge.com/minecraft/mc-mods/lendercataclysm'},
    { name: 'Get It Together, Drops!', author: 'bl4ckscor3', url: 'https://www.curseforge.com/minecraft/mc-mods/get-it-together-drops'},
    { name: 'MrCrayfish\'s Gun Mod [Unofficial]', author: 'MikhailTapio', url: 'https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-gun-mod-unofficial'},
    { name: 'Macaw\'s Paintings', author: 'sketch_macaw', url: 'https://www.curseforge.com/minecraft/mc-mods/macaws-paintings'},
    { name: 'Create Enchantment Industry', author: 'DragonsPlus', url: 'https://www.curseforge.com/minecraft/mc-mods/create-enchantment-industry'},
    { name: 'Charm of Undying (Fabric/Forge/Quilt)', author: 'TheIllusiveC4', url: 'https://www.curseforge.com/minecraft/mc-mods/charm-of-undying'},
    { name: 'Inventory Pets', author: 'Purplicious_Cow_', url: 'https://www.curseforge.com/minecraft/mc-mods/inventory-pets'},
    { name: 'Max Health Fix', author: 'DarkhaxDev', url: 'https://www.curseforge.com/minecraft/mc-mods/max-health-fix'},
    { name: 'Extreme Reactors', author: 'ZeroNoRyouki', url: 'https://www.curseforge.com/minecraft/mc-mods/extreme-reactors'},
    { name: 'Mob Despawn Timers', author: 'Shadows_of_Fire', url: 'https://www.curseforge.com/minecraft/mc-mods/mob-despawn-timers'},
    { name: 'Trash Cans', author: 'SuperMartijn642', url: 'https://www.curseforge.com/minecraft/mc-mods/trash-cans'},
    { name: 'ATO - All the Ores', author: 'ATMTeam', url: 'https://www.curseforge.com/minecraft/mc-mods/ato'},
    { name: 'Ranged Pumps', author: 'raoulvdberge', url: 'https://www.curseforge.com/minecraft/mc-mods/ranged-pumps'},
    { name: 'Ad Astra: Giselle Addon', author: 'gisellevonbingen', url: 'https://www.curseforge.com/minecraft/mc-mods/ad-astra-giselle-addon'},
    { name: 'Useful Railroads', author: 'HyCraftHD', url: 'https://www.curseforge.com/minecraft/mc-mods/useful-railroads'},
]